---
language: python

python:
  #- "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install wareztool
  # Coveralls 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - pip install coveralls
  - pip install .

script:
  # Test for Syntax
  - coverage run --source=wareztools setup.py test
  - nosetests

after_success:
  - coveralls
