---
language: python
python:
  #- "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install wareztool
  - pip install coveralls
  - pip install .

script:
  # Test for Syntax
  - ls -R /usr/lib/python*
  - ls -R /usr/lib64/python*
  - coverage run --source=wareztools setup.py test
  - nosetests

after_success:
  - coveralls
